### ISSUE TITLE
Gateway cannot be found anymore after update to HA 2023.8.4

### ISSUE THREAD

**Issue by midget1234** [jbouwh/incomfort-client#10]
<img width="1190" alt="Scherm­afbeelding 2023-08-31 om 20 01 13" src="https://github.com/zxdavb/incomfort-client/assets/13736772/8f5565b4-a65f-4658-bb33-5eff214393ad">

HA does not recognized the heater anymore... (after years of working perfectly).

**Comment by midget1234** [comment]
It was not an HA Integration issue but a Intergas Issue.. All good now

**Comment by DigiLive** [comment]
@midget1234 How did you resolve this issue?

**Comment by jbouwh** [comment]
Closing as this is stale. This type of error will be handled better from HA Core 2024.6.
