### ISSUE TITLE
Fix proposal for CLIENT_TIMEOUT value too low

### ISSUE THREAD

**Issue by SenTzu01** [jbouwh/incomfort-client#11]
Please see below as reference for a fix in regards to Home Assistant Core issue [#110140](https://github.com/home-assistant/core/issues/110140)
I have been able to work around this until a fixture can be applied:
Workaround is to set timeout in the incomfortclient library to a sufficiently high value. Downside is this needs to be reapplied after every Home Assistant Core update.

docker exec command to achieve this is:

` docker exec -it  homeassistant  sh "/bin/sed -i 's/CLIENT_TIMEOUT = 20/CLIENT_TIMEOUT = 300/g' /usr/local/lib/python3.12/site-packages/incomfortclient/__init__.py"`
Alternatively one could create a shell command which can be triggered per the usual ways:

```
shell_command:
  fix_incomfort: /bin/sed -i 's/CLIENT_TIMEOUT = 20/CLIENT_TIMEOUT = 300/g' /usr/local/lib/python3.12/site-packages/incomfortclient/__init__.py
```

**Comment by NH-Networks** [comment]
If a timeout of 300 sec is needed to make it work.. then there is something seriously wrong.. 

Suggest to find real issue instead of this workaround

**Comment by zxdavb** [comment]
> If a timeout of 300 sec is needed to make it work.. then there is something seriously wrong..

I agree: I think this is OK as a workaround, but should not become part of the library.

**Comment by jbouwh** [comment]
Closing this PR as it is not going to be implemented.
