### ISSUE TITLE
Does this also work on the new gateway?

### ISSUE THREAD

**Issue by ghost** [jbouwh/incomfort-client#7]
I mean this [one sometimes called gateway II](https://www.intergas-verwarming.nl/app/uploads/2018/02/Gebruiks-en-Installatiehandleiding-Intergas-Gateway-842014-00.pdf)

Second question do you need an internet connection or can you still communicate when internet is down?

**Comment by zxdavb** [comment]
I do not know, 

The place to ask may be in the Home Assistant community forum, where it is an officially supported integration:
https://community.home-assistant.io/search?q=incomfort

**Comment by KeningGruttePier** [comment]
> I mean this [one sometimes called gateway II](https://www.intergas-verwarming.nl/app/uploads/2018/02/Gebruiks-en-Installatiehandleiding-Intergas-Gateway-842014-00.pdf)
> 
> Second question do you need an internet connection or can you still communicate when internet is down?

You refer to 2018 documentation in your URL. Could you disclose more about this "gateway 2"? 
I run the gateway as depicted in your online documentation + incomfort integration in HA. No issue. 

2) Yes. HA will still send commands internally tru the gateway to your CV. And is able to update the entities when you external internet connection is down.

**Comment by jbouwh** [comment]
Closing as this is stale IMO
